Update 25.12-C2.yml

diff --git a/.github/workflows/25.12-C2.yml b/.github/workflows/25.12-C2.yml
--- a/.github/workflows/25.12-C2.yml
+++ b/.github/workflows/25.12-C2.yml
@@ -1,4 +1,4 @@
-name: 25.12-C2
+name: 25.12-C
 
 on:
   repository_dispatch:
@@ -16,6 +16,7 @@ env:
   TZ: Asia/Shanghai
   UPLOAD_RELEASE: 'true'
   DEBIAN_FRONTEND: noninteractive
+  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
 
 jobs:
   build:
@@ -71,8 +72,17 @@ jobs:
         echo "::endgroup::"
 
         echo "::group::apt-get install"
-        DEPS=$(curl -fsSL https://raw.githubusercontent.com/ham-0915/N1-0325/refs/heads/main/N1/Immortalwrt/25.12/2512)
-        sudo -E apt-get -qq install $DEPS ccache || { echo "::error::apt-get install 失败"; exit 1; }
+        sudo -E apt-get -qq install \
+          ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
+          bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk \
+          gettext gcc-multilib g++-multilib git gnutls-dev gperf haveged help2man intltool \
+          libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev \
+          libmpfr-dev libncurses-dev libpython3-dev libreadline-dev libssl-dev libtool \
+          libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano ninja-build p7zip \
+          p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
+          python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig \
+          texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd libfuse-dev \
+          || { echo "::error::apt-get install 失败"; exit 1; }
         echo "::endgroup::"
 
         echo "::group::设置时区"
@@ -90,7 +100,7 @@ jobs:
         echo "::endgroup::"
 
     - name: 恢复 Ccache 缓存
-      uses: actions/cache@v4
+      uses: actions/cache@v5
       with:
         path: ~/.ccache
         key: ${{ runner.os }}-ccache-${{ hashFiles(env.CONFIG_FILE) }}
@@ -229,3 +239,4 @@ jobs:
         delete_tags: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        
